import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza',
    cookTime: '15-20',
    price: 120,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
    // Restaurant: "la pino'z pizza",
    // rstid: '2'
  },
  {
    id:'2',
    name: 'Manchurian',
    price: 90,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'FastFood'],
    // Restaurant: 'Mama Mia'
  },
  {
    id:'3',
    name: 'Burger',
    price: 150,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
    // Restaurant: 'The Burger Bar'
  },
  {
    id:'4',
    name: 'French Fries',
    price: 90,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.5,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
    // Restaurant: 'McDonald\'s'
  },
  {
    id:'5',
    name: 'Vegetable Soup',
    price: 60,
    cookTime: '40',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
    // Restaurant: 'Le Petit Chateau'
  },
   {
    id:'6',
    name: 'Vegetables Pizza',
    price: 190,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 140,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 180,
    cookTime: '45',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'9',
    name: 'Veg. Biryani',
    price: 80,
    cookTime: '45-50',
    favorite: false,
    origins: ['Indian'],
    stars: 4.2,
    imageUrl: 'assets/food-9.png',
    tags: ['Food', 'Biryani', 'Lunch','Dinner'],
  },
  {
    id:'10',
    name: 'Pav Bhaji',
    price: 110,
    cookTime: '45',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-10.jpg',
    tags: ['FastFood','Dinner'],
  },
  {
    id:'11',
    name: 'Medu Vada',
    price: 30,
    cookTime: '40',
    favorite: false,
    origins: ['South Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-11.jpg',
    tags: ['FastFood', 'Break-Fast','South-Indian'],
  },
  {
    id:'12',
    name: 'Fafda- Jalebi',
    price: 50,
    cookTime: '30',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-12.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'13',
    name: 'Samosa',
    price: 20,
    cookTime: '40',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-13.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'14',
    name: 'Samosa-Chaat',
    price: 30,
    cookTime: '40',
    favorite: false,
    origins: ['indian'],
    stars: 4.1,
    imageUrl: 'assets/food-14.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'15',
    name: 'Rajvadi Kachori',
    price: 45,
    cookTime: '25',
    favorite: false,
    origins: ['indian'],
    stars: 4.2,
    imageUrl: 'assets/food-15.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'16',
    name: 'Kachori',
    price: 30,
    cookTime: '25',
    favorite: false,
    origins: ['indian'],
    stars: 3.9,
    imageUrl: 'assets/food-16.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'17',
    name: 'Pyazz kachori',
    price: 30,
    cookTime: '15',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-17.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'18',
    name: 'Katchi Dabeli',
    price: 25,
    cookTime: '10',
    favorite: false,
    origins: ['indian'],
    stars: 4.4,
    imageUrl: 'assets/food-18.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'19',
    name: 'Dal Vada',
    price: 40,
    cookTime: '30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.4,
    imageUrl: 'assets/food-19.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'20',
    name: 'Idli Sambar',
    price: 40,
    cookTime: '30',
    favorite: false,
    origins: ['South-Indian'],
    stars: 4.2,
    imageUrl: 'assets/food-20.jpg',
    tags: ['FastFood', 'Break-Fast','South-Indian'],
  },
  {
    id:'21',
    name: 'Poha',
    price: 35,
    cookTime: '20',
    favorite: false,
    origins: ['Indian'],
    stars: 4.2,
    imageUrl: 'assets/food-21.jpg',
    tags: ['Break-Fast'],
  },
  {
    id:'22',
    name: 'Misal Pav',
    price: 80,
    cookTime: '40',
    favorite: false,
    origins: ['Indian'],
    stars: 4.0,
    imageUrl: 'assets/food-22.jpg',
    tags: ['FastFood','Dinner'],
  },
  {
    id:'23',
    name: 'Sev Usal',
    price: 80,
    cookTime: '45',
    favorite: false,
    origins: ['Indian'],
    stars: 3.8,
    imageUrl: 'assets/food-23.jpg',
    tags: ['FastFood', 'Dinner'],
  },
  {
    id:'24',
    name: 'Dal Bati',
    price: 150,
    cookTime: '40',
    favorite: false,
    origins: ['Indian'],
    stars: 4.1,
    imageUrl: 'assets/food-24.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'25',
    name: 'Ragda Patties',
    price: 70,
    cookTime: '20',
    favorite: false,
    origins: ['Indian'],
    stars: 3.4,
    imageUrl: 'assets/food-25.jpg',
    tags: ['FastFood'],
  },
  {
    id:'26',
    name: 'Dal Pakwan',
    price: 70,
    cookTime: '25',
    favorite: false,
    origins: ['Sindh'],
    stars: 3.6,
    imageUrl: 'assets/food-26.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
  {
    id:'27',
    name: 'Veg. Puff',
    price: 20,
    cookTime: '10',
    favorite: false,
    origins: ['Indian'],
    stars: 3.9,
    imageUrl: 'assets/food-27.jpg',
    tags: ['FastFood', 'Break-Fast'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All'},
  { name: 'FastFood'},
  { name: 'Pizza'},
  { name: 'Lunch'},
  { name: 'SlowFood'},
  { name: 'Hamburger'},
  { name: 'Fry'},
  { name: 'Soup'},
  { name: 'Break-Fast'},
  { name: 'South-Indian'}

]
